title: "youbrightlight"
email: 
url: "youbrightlight.github.io"
future: true

kramadown:
  auto_ids: false

defaults:
  -
    scope:
      type: "posts"
    values:
      permalink: "/post/:year/:month/:day/:title"
  -
    scope:
      path: "direct"
    values:
      permalink: "/:basename"